// End-to-end checks for 1.8.0: REST + fallback, polling cache, webhook, stats/ROI with a real checkout,
// social proof, readiness, alerts (email + SMS webhook), pose check, HEIC, admin pages, WP-CLI.
const { chromium } = require('playwright');
const { execSync } = require('child_process');
const { W, URL_BASE, FIX, SHOTS, CHROME, state, wp: wpCli } = require('./config');
const fs = require('fs');
const SIMPLE = `${URL_BASE}/?post_type=product&p=${state.simple}`;
const CHECKOUT = `${URL_BASE}/?page_id=${state.checkout}`;
const wp = wpCli;
const php = (code) => wp(`eval '${code}'`);
const setting = (obj) => php(`$s=Online_Fitting_Room::settings(); foreach (json_decode(${JSON.stringify(JSON.stringify(obj))}, true) as $k=>$v) $s[$k]=$v; update_option("ofr_settings",$s);`);
const shots = `${SHOTS}/features`; fs.mkdirSync(shots, { recursive: true });
let pass = 0, fail = 0;
const check = (label, cond, extra = '') => { if (cond) { pass++; console.log('  ✓', label, extra); } else { fail++; console.log('  ✗', label, extra); } };
const ready = (page) => page.waitForFunction(() => !document.querySelector('[data-start]').disabled, null, { timeout: 30000 });
const toResult = (page) => page.waitForSelector('[data-stage="result"].is-active', { timeout: 60000 });
const isSession = (r) => /ofr_session|ofr%2Fv1%2Fsession|ofr\/v1\/session/.test((r.request().postData() || '') + r.url());
const openModal = async (page) => { await Promise.all([page.waitForResponse(isSession), page.click('.ofr-open:not(.ofr-open--sticky)')]); };
const tryOn = async (page, file) => {
  if (await page.isVisible('[data-stage="result"].is-active')) await page.click('[data-again]');
  await page.setInputFiles('[data-avatar]', file);
  if (!(await page.isChecked('[data-consent]'))) await page.check('[data-consent]');
  await ready(page);
  await page.click('[data-start]'); await toResult(page);
};

(async () => {
  php('global $wpdb; foreach (array("counters","events","logs","jobs") as $t) $wpdb->query("TRUNCATE ".OFR_DB::table($t)); foreach (array("mock_413","mock_mode","mock_block_rest","mock_mails","mock_sms","ofr_alert_log","ofr_alert_times","ofr_alert_low_sent") as $o) delete_option($o); update_option("mock_polls_needed", 2); delete_post_meta(' + state.simple + ', "_ofr_tryon_count");');
  setting({ pose_check: 'off', social_proof: 'yes', social_min: 1, limit_guest_day: 20, limit_per_user_day: 20, credit_mode: 'api', alert_events: 'low,empty,outage,daily', alert_email: 'yes', sms_provider: 'webhook', sms_webhook: URL_BASE + '/index.php?rest_route=/mock/v1/sms', sms_recipients: '۰۹۱۲۱۲۳۴۵۶۷', refund_failed: 'yes', webhook: 'no' });
  const browser = await chromium.launch(CHROME ? { executablePath: CHROME } : {});
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: 'fa-IR' });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error' && !m.text().startsWith('Failed to load resource') && !m.text().startsWith('INFO:')) errors.push(m.text()); });
  const calls = [];
  page.on('request', (r) => { if (r.method() === 'POST' && /ofr/.test(r.url() + (r.postData() || ''))) calls.push(r.url()); });

  console.log('1. REST transport, cached polling, webhook');
  await page.goto(SIMPLE);
  await openModal(page);
  await tryOn(page, `${FIX}/shirt.jpg`);
  check('try-on ran over REST (wp-json)', calls.some((u) => u.includes('rest_route=/ofr/v1/start')) && !calls.some((u) => u.includes('admin-ajax')), calls.length + ' calls');
  await page.waitForFunction(() => document.querySelector('[data-result]').complete && document.querySelector('[data-result]').naturalWidth > 0, null, { timeout: 10000 }).catch(() => {});
  check('result image served by REST', decodeURIComponent(await page.getAttribute('[data-result]', 'src')).includes('ofr/v1/result') && (await page.evaluate(() => document.querySelector('[data-result]').naturalWidth)) > 0);
  const cached = await page.evaluate(async () => {
    const f = (o) => { const b = new FormData(); Object.entries(o).forEach(([k, v]) => b.append(k, v)); return b; };
    const base = window.OnlineFittingRoom.restUrl;
    const s = await (await fetch(base + 'session', { method: 'POST', body: f({}) })).json();
    const jobs = JSON.parse(sessionStorage.getItem('ofr_jobs') || '[]');
    return { nonce: s.data.nonce, ok: !!s.success };
  });
  check('REST session endpoint answers with the envelope', cached.ok);
  const job = php('global $wpdb; $r=$wpdb->get_row("SELECT * FROM ".OFR_DB::table("jobs")." ORDER BY created DESC LIMIT 1", ARRAY_A); echo $r["prediction"];');
  const hook = php('echo OFR_Rest::webhook_url();');
  const woke = await page.evaluate(async ([url, id]) => (await (await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, status: 'succeeded' }) })).json()), [hook, job]);
  check('webhook marks the job for an immediate check', woke.ok && woke.matched === 1, JSON.stringify(woke));
  const bad = await page.evaluate(async (url) => (await fetch(url.replace(/[A-Za-z0-9]{32}$/, 'x'.repeat(32)), { method: 'POST', body: '{}' })).status, hook);
  check('webhook with wrong secret refused', bad === 404, String(bad));
  // Polling cache: two status calls in a row → the second is answered without calling the service.
  setting({ mock_dummy: 1 });
  wp('option update mock_polls_needed 50');
  await page.click('[data-again]');
  await page.setInputFiles('[data-avatar]', `${FIX}/shirt.jpg`); await ready(page);
  await page.click('[data-start]'); await page.waitForTimeout(3500);
  const token = await page.evaluate(() => (JSON.parse(sessionStorage.getItem('ofr_jobs') || '[]').find((j) => j.state === 'working') || {}).token);
  const pollTwice = await page.evaluate(async (tok) => {
    const f = (o) => { const b = new FormData(); Object.entries(o).forEach(([k, v]) => b.append(k, v)); return b; };
    const base = window.OnlineFittingRoom.restUrl;
    const s = await (await fetch(base + 'session', { method: 'POST', body: f({}) })).json();
    const a = await (await fetch(base + 'status', { method: 'POST', body: f({ nonce: s.data.nonce, job: tok }) })).json();
    const b = await (await fetch(base + 'status', { method: 'POST', body: f({ nonce: s.data.nonce, job: tok }) })).json();
    return [a.data, b.data];
  }, token);
  check('rapid repeat poll served from cache (no upstream call)', pollTwice[1] && pollTwice[1].cached === true, JSON.stringify(pollTwice));
  check('poll interval grows as the try-on ages', Number(pollTwice[1].retryAfter) >= 2);
  wp('option update mock_polls_needed 2');
  await page.keyboard.press('Escape');
  await page.evaluate(() => sessionStorage.clear()); // The long job above would otherwise resume on the next page (by design).

  console.log('2. REST blocked by a security plugin → automatic admin-ajax fallback');
  wp('option update mock_block_rest 1');
  calls.length = 0;
  await page.goto(SIMPLE); await openModal(page);
  await tryOn(page, `${FIX}/shirt.jpg`);
  check('try-on completed via admin-ajax fallback', calls.some((u) => u.includes('admin-ajax')) && (await page.getAttribute('[data-result]', 'src')).includes('admin-ajax'));
  wp('option delete mock_block_rest');
  await page.keyboard.press('Escape');

  console.log('3. Social proof, add to cart after try-on, real checkout → order meta and ROI');
  php('OFR_Stats::refresh_count(' + state.simple + ');');
  await page.goto(SIMPLE);
  const proof = await page.textContent('.ofr-proof').catch(() => '');
  check('social proof under the button', /نفر این لباس را پرو کردند/.test(proof), proof);
  await openModal(page);
  check('social proof in the modal', /پرو کردند/.test(await page.textContent('[data-product-proof]')));
  await tryOn(page, `${FIX}/shirt.jpg`);
  await page.click('[data-cart]');
  await page.waitForTimeout(1500);
  const carts = Number(php('global $wpdb; echo $wpdb->get_var("SELECT COUNT(*) FROM ".OFR_DB::table("events")." WHERE type=\\"cart\\"");'));
  check('add-to-cart after try-on recorded', carts >= 1, String(carts));
  await page.keyboard.press('Escape');
  await page.goto(CHECKOUT);
  await page.fill('#billing_first_name', 'Ali'); await page.fill('#billing_last_name', 'Test');
  await page.fill('#billing_address_1', '1 Test St'); await page.fill('#billing_city', 'LA');
  await page.fill('#billing_postcode', '90210'); await page.fill('#billing_phone', '09121234567'); await page.fill('#billing_email', 'buyer@example.com');
  if (await page.locator('#billing_state').count()) await page.selectOption('#billing_state', 'CA').catch(() => {});
  await page.waitForTimeout(1500);
  const cod = page.locator('#payment_method_cod'); if (await cod.count()) await cod.check().catch(() => {});
  await page.click('#place_order');
  await page.waitForURL(/order-received/, { timeout: 30000 }).catch(() => {});
  const order = JSON.parse(php('$o = wc_get_orders(array("limit"=>1,"orderby"=>"date","order"=>"DESC"))[0]; $item = current($o->get_items()); echo json_encode(array("status"=>$o->get_status(),"meta"=>$o->get_meta("_ofr_tryon"),"item"=>$item->get_meta("_ofr_tryon")));'));
  check('paid order marked as try-on order (order + line meta)', order.meta === 'yes' && order.item === 'yes', JSON.stringify(order));
  const sum = JSON.parse(php('echo json_encode(OFR_Stats::summary(30));'));
  check('ROI summary counts try-ons, carts, orders and revenue', sum.successes >= 3 && sum.carts >= 1 && sum.orders === 1 && sum.revenue > 0, JSON.stringify(sum));

  console.log('4. Alerts: low balance (manual credits), exhausted (402), email + SMS webhook');
  setting({ credit_mode: 'manual', credits_bought: 3, credits_threshold: 2 });
  php('OFR_Alerts::reset_manual();');
  await page.goto(SIMPLE); await openModal(page);
  await tryOn(page, `${FIX}/shirt.jpg`);
  await tryOn(page, `${FIX}/shirt.jpg`);
  const mails = JSON.parse(php('echo json_encode(get_option("mock_mails", array()));'));
  const sms = JSON.parse(php('echo json_encode(get_option("mock_sms", array()));'));
  check('low-balance email sent once', mails.filter((m) => /رو به پایان/.test(m.message)).length === 1, mails.length + ' mails');
  check('low-balance SMS via webhook with normalized number', sms.some((m) => /رو به پایان/.test(m.message) && m.recipients[0] === '09121234567'), JSON.stringify(sms.slice(-1)));
  wp('option update mock_mode nocredit');
  await page.click('[data-again]');
  await page.setInputFiles('[data-avatar]', `${FIX}/shirt.jpg`); await ready(page); await page.click('[data-start]');
  await page.waitForSelector('.ofr__error:not([hidden])', { timeout: 30000 });
  const mails2 = JSON.parse(php('echo json_encode(get_option("mock_mails", array()));'));
  check('credit-exhausted (402) alert sent', mails2.some((m) => /تمام شده/.test(m.message)));
  wp('option delete mock_mode');
  php('OFR_Alerts::daily_report();');
  check('daily report sent', JSON.parse(php('echo json_encode(get_option("mock_sms", array()));')).some((m) => /گزارش امروز/.test(m.message)));
  setting({ credit_mode: 'api' });
  check('balance read from the service (api mode)', php('echo OFR_Alerts::balance(true)["value"];') === '120');
  await page.keyboard.press('Escape');

  console.log('5. Photo check (pose) and HEIC');
  setting({ pose_check: 'warn' });
  await page.goto(SIMPLE); await openModal(page);
  if (await page.isVisible('[data-stage="result"].is-active')) await page.click('[data-again]');
  await page.setInputFiles('[data-avatar]', `${FIX}/person-full.jpg`);
  await page.waitForFunction(() => { const el = document.querySelector('[data-photo-check]'); return el && !el.hidden && el.dataset.kind && el.dataset.kind !== 'info'; }, null, { timeout: 60000 });
  check('full-body photo passes the check', (await page.getAttribute('[data-photo-check]', 'data-kind')) === 'ok', await page.textContent('[data-photo-check]'));
  await page.screenshot({ path: `${shots}/1-pose-ok.png` });
  await page.click('[data-change]').catch(() => {});
  await page.setInputFiles('[data-avatar]', `${FIX}/person-half.jpg`);
  await page.waitForFunction(() => { const el = document.querySelector('[data-photo-check]'); return el && !el.hidden && el.dataset.kind && el.dataset.kind !== 'info'; }, null, { timeout: 30000 });
  check('half-body photo warned', (await page.getAttribute('[data-photo-check]', 'data-kind')) === 'warn' && /تمام‌قد نیست/.test(await page.textContent('[data-photo-check]')), await page.textContent('[data-photo-check]'));
  await page.screenshot({ path: `${shots}/2-pose-partial.png` });
  await page.keyboard.press('Escape');
  setting({ pose_check: 'block' });
  await page.goto(SIMPLE); await openModal(page);
  if (await page.isVisible('[data-stage="result"].is-active')) await page.click('[data-again]');
  await page.setInputFiles('[data-avatar]', `${FIX}/shirt.jpg`);
  await page.waitForFunction(() => { const el = document.querySelector('[data-photo-check]'); return el && !el.hidden && el.dataset.kind && el.dataset.kind !== 'info'; }, null, { timeout: 30000 });
  await page.check('[data-consent]').catch(() => {});
  check('block mode: no person → start disabled', (await page.getAttribute('[data-photo-check]', 'data-kind')) === 'error' && await page.isDisabled('[data-start]'), await page.textContent('[data-photo-check]'));
  await page.keyboard.press('Escape');
  setting({ pose_check: 'warn' });
  await page.goto(SIMPLE); await openModal(page);
  if (await page.isVisible('[data-stage="result"].is-active')) await page.click('[data-again]');
  await page.setInputFiles('[data-avatar]', `${FIX}/person.heic`);
  await page.waitForFunction(() => document.querySelector('[data-preview]').src.startsWith('blob:'), null, { timeout: 60000 });
  const heicPreview = await page.evaluate(() => document.querySelector('[data-preview]').naturalWidth);
  check('iPhone HEIC decoded in the browser with the new decoder', heicPreview > 500, `(${heicPreview}px)`);
  await page.waitForFunction(() => { const el = document.querySelector('[data-photo-check]'); return el && !el.hidden && el.dataset.kind && el.dataset.kind !== 'info'; }, null, { timeout: 60000 }).catch(() => {});
  check('HEIC photo also passes the pose check', (await page.getAttribute('[data-photo-check]', 'data-kind')) === 'ok');
  await ready(page); await page.click('[data-start]'); await toResult(page);
  const sent = fs.readFileSync(`${W}/wp-content/mock-person.bin`);
  check('HEIC sent to the service as JPEG', sent[0] === 0xff && sent[1] === 0xd8);
  await page.keyboard.press('Escape');

  console.log('6. Logged-in customer over REST (X-WP-Nonce)');
  php('if (!get_user_by("login","buyer")) wp_create_user("buyer","buyerpass","buyer2@example.com");');
  const c2 = await browser.newContext({ viewport: { width: 1280, height: 900 } });
  const p2 = await c2.newPage();
  await p2.goto(URL_BASE + '/wp-login.php'); await p2.fill('#user_login', 'buyer'); await p2.fill('#user_pass', 'buyerpass'); await p2.click('#wp-submit'); await p2.waitForLoadState('networkidle');
  const urls = []; p2.on('request', (r) => { if (r.method() === 'POST') urls.push(r.url()); });
  await p2.goto(SIMPLE);
  check('logged-in page carries a REST nonce', !!(await p2.evaluate(() => window.OnlineFittingRoom.restNonce)));
  await openModal(p2); await tryOn(p2, `${FIX}/shirt.jpg`);
  const userEvents = php('global $wpdb; $v = substr(hash_hmac("sha256","ofr-visitor|user:".get_user_by("login","buyer")->ID, wp_salt("nonce")),0,32); echo $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM ".OFR_DB::table("events")." WHERE visitor=%s", $v));');
  check('member try-on over REST counted for the member', Number(userEvents) >= 2 && urls.some((u) => u.includes('rest_route=/ofr/v1/start')), userEvents);

  console.log('7. Admin pages');
  const a = await browser.newContext({ viewport: { width: 1400, height: 1000 } });
  const ap = await a.newPage();
  ap.on('pageerror', (e) => errors.push('admin: ' + e.message));
  await ap.goto(URL_BASE + '/wp-login.php'); await ap.fill('#user_login', 'admin'); await ap.fill('#user_pass', 'admin'); await ap.click('#wp-submit'); await ap.waitForLoadState('networkidle');
  await ap.goto(URL_BASE + '/wp-admin/admin.php?page=online-fitting-room&tab=stats');
  check('stats tab: KPI tiles and bars', await ap.locator('.ofr-stats--5 .ofr-stat').count() === 5 && await ap.locator('.ofr-chart__bar').count() >= 1);
  await ap.hover('.ofr-chart__col:last-of-type').catch(() => {});
  await ap.screenshot({ path: `${shots}/3-stats.png`, fullPage: true });
  await ap.goto(URL_BASE + '/wp-admin/admin.php?page=online-fitting-room&tab=readiness');
  check('readiness tab lists products with status', await ap.locator('.ofr-ready tbody tr').count() >= 2);
  await ap.screenshot({ path: `${shots}/4-readiness.png`, fullPage: true });
  await ap.goto(URL_BASE + '/wp-admin/admin.php?page=online-fitting-room&tab=alerts');
  await ap.click('[data-ofr-action="ofr_test_alert"][data-channel="sms"]');
  await ap.waitForSelector('#ofr-test-result:not([hidden])');
  check('alerts tab: test SMS works', (await ap.getAttribute('#ofr-test-result', 'class')).includes('ok'), await ap.textContent('#ofr-test-result'));
  await ap.screenshot({ path: `${shots}/5-alerts.png`, fullPage: true });
  await ap.fill('#ofr-threshold', '7');
  await ap.click('.ofr-savebar button[type=submit]'); await ap.waitForLoadState('networkidle');
  const after = JSON.parse(php('$s=Online_Fitting_Room::settings(); echo json_encode(array($s["credits_threshold"],$s["enabled"],$s["photo_guide"],$s["sms_provider"]));'));
  check('saving the alerts tab keeps the other settings', after[0] === 7 && after[1] === 'yes' && after[2] === 'yes' && after[3] === 'webhook', JSON.stringify(after));
  await ap.goto(URL_BASE + '/wp-admin/admin.php?page=online-fitting-room&tab=logs');
  check('logs tab shows entries', await ap.locator('.ofr-logs tbody tr').count() >= 1);
  await ap.goto(URL_BASE + '/wp-admin/admin.php?page=online-fitting-room');
  check('settings tab still renders (credit card, experience card)', await ap.locator('#ofr-experience').count() === 1 && await ap.locator('[data-ofr-balance]').count() === 1);
  await ap.screenshot({ path: `${shots}/6-settings.png`, fullPage: true });

  console.log('8. WP-CLI');
  check('wp ofr stats', /successes/.test(wp('ofr stats --days=7')));
  check('wp ofr health', /imagick/.test(wp('ofr health')));
  check('wp ofr readiness', /ready|warning/.test(wp('ofr readiness')));

  check('no JS errors', errors.length === 0, errors.join(' | '));
  await browser.close();
  console.log(`\npassed ${pass}, failed ${fail}`);
  process.exit(fail ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
