// End-to-end checks for 1.7.0 (UI + UX features) against the local WordPress with the mocked API.
const { chromium } = require('playwright');
const { execSync } = require('child_process');
const { W, URL_BASE, FIX, SHOTS, CHROME, state, wp: wpCli } = require('./config');
const fs = require('fs');
const SIMPLE = `${URL_BASE}/?post_type=product&p=${state.simple}`;
const VID = state.variable;
const VARIABLE = `${URL_BASE}/?post_type=product&p=${VID}`;
const md5 = (f) => require('crypto').createHash('md5').update(fs.readFileSync(f)).digest('hex');
const wp = wpCli;
const setting = (obj) => wp(`eval '$s=Online_Fitting_Room::settings(); foreach (json_decode(${JSON.stringify(JSON.stringify(obj))}, true) as $k=>$v) $s[$k]=$v; update_option("ofr_settings",$s);'`);
const resetCounters = () => wp(`eval 'global $wpdb; $wpdb->query("TRUNCATE ".OFR_Quota::table());'`);
const shots = `${SHOTS}/ux`; fs.mkdirSync(shots, { recursive: true });
let pass = 0, fail = 0;
const check = (label, cond, extra = '') => { if (cond) { pass++; console.log('  ✓', label, extra); } else { fail++; console.log('  ✗', label, extra); } };
const ready = (page) => page.waitForFunction(() => !document.querySelector('[data-start]').disabled, null, { timeout: 30000 });
const toResult = (page) => page.waitForSelector('[data-stage="result"].is-active', { timeout: 60000 });
const sessionDone = (page) => page.waitForResponse((r) => /ofr_session|ofr%2Fv1%2Fsession|ofr\/v1\/session/.test((r.request().postData() || '') + r.url()));

(async () => {
  resetCounters();
  wp(`eval 'foreach (["mock_413","mock_413_hits","mock_posts","mock_mode"] as $o) delete_option($o); update_option("mock_polls_needed", 2);'`);
  setting({ api_key: 'vton_live_testkey123456789', modal_title: 'پروی هوشمند فروشگاه', theme_mode: 'light', button_position: 'summary', loop_badge: 'no', sticky_mobile: 'yes', limit_guest_day: 5, limit_per_user_day: 5 });
  const browser = await chromium.launch(CHROME ? { executablePath: CHROME } : {});
  const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 }, locale: 'fa-IR' });
  // Capture what would be shared (navigator.share is not available in headless Linux).
  await ctx.addInitScript(() => {
    window.__shared = null;
    navigator.canShare = () => true;
    navigator.share = async (data) => { const f = data.files && data.files[0]; window.__shared = f ? { type: f.type, size: f.size, text: data.text } : { text: data.text }; };
  });
  const page = await ctx.newPage();
  const errors = [];
  page.on('pageerror', (e) => errors.push(e.message));
  page.on('console', (m) => { if (m.type() === 'error' && !m.text().startsWith('Failed to load resource') && !m.text().startsWith('INFO:')) errors.push(m.text()); });

  console.log('1. Modal: custom title, guide image, viewer, consent link');
  await page.goto(SIMPLE);
  await Promise.all([sessionDone(page), page.click('.ofr-open')]);
  check('custom modal title', (await page.textContent('#ofr-title')) === 'پروی هوشمند فروشگاه');
  check('guide shows the supplied image', (await page.getAttribute('[data-guide] img', 'src')).includes('photo-guide-small.webp'));
  check('old SVG cards gone', await page.locator('.ofr__guide-item').count() === 0);
  await page.click('[data-zoom-guide]');
  await page.waitForSelector('[data-viewer]:not([hidden])');
  check('guide opens full size in viewer', (await page.getAttribute('[data-viewer-img]', 'src')).includes('photo-guide.webp'));
  await page.screenshot({ path: `${shots}/1-guide-viewer.png` });
  await page.keyboard.press('Escape');
  check('Esc closes viewer, modal stays', await page.isHidden('[data-viewer]') && await page.isVisible('.ofr__dialog'));
  const link = page.locator('.ofr__consent a');
  check('consent links to privacy policy in new tab', (await link.count()) === 1 && (await link.getAttribute('href')).includes('page_id=3') && (await link.getAttribute('target')) === '_blank');
  await page.screenshot({ path: `${shots}/2-upload.png` });

  console.log('2. Photo kept on device, scan screen, estimated progress, before/after');
  await page.setInputFiles('[data-avatar]', `${FIX}/generated/person-gps.jpg`);
  await page.check('[data-remember]'); await page.check('[data-consent]'); await ready(page);
  wp('option update mock_polls_needed 3');
  await page.click('[data-start]');
  await page.waitForSelector('[data-stage="working"].is-active');
  await page.waitForTimeout(1500);
  check('scan shows shopper photo and garment', (await page.getAttribute('[data-scan-photo]', 'src')).startsWith('blob:') && (await page.getAttribute('[data-scan-garment]', 'src')).includes('shirt'));
  const width = await page.evaluate(() => parseFloat(document.querySelector('[data-meter] span').style.width));
  check('estimated progress moves', width > 0, `(${width}%)`);
  check('ETA text shown', (await page.textContent('[data-eta]')).length > 3);
  await page.screenshot({ path: `${shots}/3-scan.png` });
  await toResult(page);
  check('before/after slider visible', await page.isVisible('[data-compare]') && (await page.getAttribute('[data-before]', 'src')).startsWith('blob:'));
  await page.evaluate(() => { const r = document.querySelector('[data-compare]'); r.value = 25; r.dispatchEvent(new Event('input', { bubbles: true })); });
  check('slider moves the split', (await page.evaluate(() => document.querySelector('[data-compare-view]').style.getPropertyValue('--pos'))) === '25%');
  await page.screenshot({ path: `${shots}/4-result-slider.png` });
  await page.click('[data-zoom-result]');
  await page.waitForSelector('[data-viewer]:not([hidden])');
  await page.mouse.move(640, 450); await page.mouse.wheel(0, -400); await page.waitForTimeout(300);
  const scale = await page.evaluate(() => Number((document.querySelector('[data-viewer-img]').style.transform.match(/scale\(([\d.]+)\)/) || [])[1]));
  check('fullscreen viewer zooms', scale > 1.2, `(×${scale && scale.toFixed(2)})`);
  await page.mouse.dblclick(640, 450).catch(() => {});
  await page.keyboard.press('Escape');
  const stored = await page.evaluate(() => new Promise((res) => { const o = indexedDB.open('ofr', 1); o.onsuccess = () => { const r = o.result.transaction('photo').objectStore('photo').get('me'); r.onsuccess = () => res(r.result ? r.result.blob.size : 0); }; }));
  check('photo kept in this browser only (IndexedDB)', stored > 0, `(${Math.round(stored / 1024)} KB)`);

  console.log('3. Retry with same photo, share with watermark, compare');
  wp('option update mock_polls_needed 2');
  const postsBefore = Number(wp('option get mock_posts'));
  await page.click('[data-retry]');
  await toResult(page);
  check('retry with same photo ran another try-on', Number(wp('option get mock_posts')) === postsBefore + 1);
  await page.click('[data-share]');
  await page.waitForFunction(() => window.__shared, null, { timeout: 15000 });
  const shared = await page.evaluate(() => window.__shared);
  check('share sends a JPEG file with product link', shared.type === 'image/jpeg' && shared.size > 1000 && shared.text.includes(new URL(URL_BASE).host), JSON.stringify(shared));
  check('compare button counts results', (await page.textContent('[data-open-compare]')).includes('2'));
  await page.click('[data-open-compare]');
  await page.waitForSelector('[data-stage="compare"].is-active');
  check('side-by-side comparison of try-ons', await page.locator('.ofr__tile').count() === 2);
  await page.screenshot({ path: `${shots}/5-compare.png` });
  await page.click('[data-back-result]');

  console.log('4. Next visit: saved photo and consent ready, one click');
  await page.goto(SIMPLE);
  await Promise.all([sessionDone(page), page.click('.ofr-open')]);
  await page.waitForSelector('[data-saved-badge]:not([hidden])', { timeout: 10000 });
  check('saved photo restored, consent remembered', await page.isChecked('[data-consent]') && await page.isChecked('[data-remember]'));
  await ready(page);
  await page.screenshot({ path: `${shots}/6-saved-photo.png` });
  wp('option update mock_413 300000'); wp('option update mock_413_hits 0');
  await page.click('[data-start]');
  await toResult(page);
  check('saved photo + 413 → lighter retry succeeded', Number(wp('option get mock_413_hits')) === 1);
  wp('option delete mock_413');
  await page.click('[data-again]').catch(() => {});
  await page.keyboard.press('Escape');
  await Promise.all([sessionDone(page), page.click('.ofr-open')]);
  await page.waitForSelector('[data-forget]:not([hidden])', { timeout: 10000 }).catch(() => {});
  if (await page.isVisible('[data-forget]')) await page.click('[data-forget]');
  const left = await page.evaluate(() => new Promise((res) => { const o = indexedDB.open('ofr', 1); o.onsuccess = () => { const r = o.result.transaction('photo').objectStore('photo').get('me'); r.onsuccess = () => res(!!r.result); }; }));
  check('«حذف از این دستگاه» erases it', !left && await page.isVisible('[data-drop]'));
  await page.keyboard.press('Escape');

  console.log('5. Colour swatches in the modal (variable product)');
  await page.goto(VARIABLE);
  await Promise.all([sessionDone(page), page.click('.ofr-open')]);
  await page.waitForSelector('[data-swatches]:not([hidden])');
  check('two swatches named by colour only', (await page.locator('[data-swatches] .ofr__swatch').allTextContents()).join('|') === 'قرمز|آبی');
  await page.click('[data-swatches] .ofr__swatch:nth-child(2)');
  check('swatch updates garment image and title', (await page.getAttribute('[data-product-image]', 'src')).includes('shirt-blue') && (await page.textContent('[data-product-title]')).includes('آبی'));
  check('page form follows the colour', (await page.inputValue('select[name="attribute_pa_color"]')) === 'blue');
  await page.screenshot({ path: `${shots}/7-swatches.png` });
  await page.setInputFiles('[data-avatar]', `${FIX}/shirt.jpg`); await ready(page);
  await page.click('[data-start]'); await toResult(page);
  check('blue garment image sent to the service', wp('option get mock_garment_md5') === md5(`${FIX}/shirt-blue.jpg`));
  await page.click('[data-result-swatches] .ofr__swatch:nth-child(1)');
  await page.waitForSelector('[data-stage="working"].is-active');
  await toResult(page);
  check('result swatch re-runs with red, same photo', wp('option get mock_garment_md5') === md5(`${FIX}/shirt.jpg`));
  await page.screenshot({ path: `${shots}/8-result-swatches.png` });
  await page.keyboard.press('Escape');

  console.log('6. Guest limit → login invitation');
  resetCounters(); setting({ limit_guest_day: 1, limit_per_user_day: 5 });
  await page.goto(SIMPLE);
  await Promise.all([sessionDone(page), page.click('.ofr-open')]);
  await page.waitForFunction(() => (document.querySelector('[data-remaining]').textContent || '').includes('ورود'), null, { timeout: 5000 }).catch(() => {});
  check('remaining line advertises member allowance', (await page.textContent('[data-remaining]')).includes('ورود'));
  for (let i = 0; i < 2; i++) {
    await page.click('[data-again]').catch(() => {});
    if (await page.isVisible('[data-stage="result"].is-active')) await page.click('[data-again]');
    await page.setInputFiles('[data-avatar]', `${FIX}/shirt.jpg`); await ready(page);
    await page.click('[data-start]');
    await page.waitForSelector('[data-stage="result"].is-active, .ofr__error:not([hidden])', { timeout: 60000 });
  }
  const upsell = page.locator('[data-upsell]');
  check('quota message offers login with member allowance', await upsell.isVisible() && /[5۵]/.test(await upsell.textContent()) && (await upsell.getAttribute('href')).includes('page_id='), await upsell.textContent().catch(() => ''));
  await page.screenshot({ path: `${shots}/9-upsell.png` });
  setting({ limit_guest_day: 5 }); resetCounters();
  await page.keyboard.press('Escape');

  console.log('7. Background job + toast still work');
  await page.click('.ofr-open'); await page.click('[data-again]').catch(() => {});
  if (!(await page.isVisible('[data-drop]'))) await page.click('[data-again]').catch(() => {});
  await page.setInputFiles('[data-avatar]', `${FIX}/shirt.jpg`); await ready(page);
  wp('option update mock_polls_needed 3');
  await page.click('[data-start]'); await page.waitForSelector('[data-stage="working"].is-active');
  await page.click('[data-background]');
  await page.waitForSelector('[data-ofr-toast][data-state="done"]', { timeout: 60000 });
  check('toast after closing mid-way', true);
  await page.click('[data-toast-close]');
  wp('option update mock_polls_needed 2');

  console.log('8. «قابل پرو» badge on the shop page opens the try-on there');
  setting({ loop_badge: 'yes' });
  await page.goto(URL_BASE + '/?post_type=product');
  const badges = await page.locator('[data-ofr-open]').count();
  check('badges on product cards', badges >= 2, `(${badges})`);
  await page.screenshot({ path: `${shots}/10-shop-badges.png` });
  const before = page.url();
  await page.locator('[data-ofr-open]').first().click();
  await page.waitForSelector('.ofr:not([hidden])');
  check('badge opens modal without leaving the shop', page.url() === before);
  await page.keyboard.press('Escape');
  setting({ loop_badge: 'no' });

  console.log('9. Button positions');
  setting({ button_position: 'gallery' });
  await page.goto(SIMPLE); await page.waitForLoadState('load'); await page.waitForTimeout(500);
  check('gallery position: button over the product image', await page.evaluate(() => !!document.querySelector('.woocommerce-product-gallery .ofr-open')));
  await page.screenshot({ path: `${shots}/11-gallery-button.png` });
  setting({ button_position: 'after_cart' });
  await page.goto(SIMPLE);
  check('after add-to-cart position', await page.evaluate(() => { const f = document.querySelector('form.cart'); const b = document.querySelector('.ofr-open--after_cart'); return !!(f && b && (f.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING)); }));
  setting({ button_position: 'summary' });

  console.log('10. Dark mode');
  setting({ theme_mode: 'dark' });
  await page.goto(SIMPLE); await page.click('.ofr-open');
  const bg = await page.evaluate(() => getComputedStyle(document.querySelector('.ofr__dialog')).backgroundColor);
  check('dark dialog background', bg === 'rgb(20, 22, 28)', bg);
  await page.screenshot({ path: `${shots}/12-dark.png` });
  await page.keyboard.press('Escape');
  setting({ theme_mode: 'light' });

  console.log('11. Mobile: sticky bar, layout');
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, locale: 'fa-IR' });
  const m = await mobile.newPage();
  m.on('pageerror', (e) => errors.push('mobile: ' + e.message));
  await m.goto(SIMPLE);
  check('sticky bar hidden at top', !(await m.evaluate(() => document.querySelector('[data-ofr-sticky]').classList.contains('is-visible'))));
  await m.evaluate(() => window.scrollTo(0, document.body.scrollHeight)); await m.waitForTimeout(600);
  check('sticky bar appears after scrolling past the button', await m.evaluate(() => document.querySelector('[data-ofr-sticky]').classList.contains('is-visible')));
  await m.screenshot({ path: `${shots}/13-mobile-sticky.png` });
  await m.click('.ofr-open--sticky'); await m.waitForSelector('.ofr:not([hidden])');
  await m.screenshot({ path: `${shots}/14-mobile-modal.png` });
  await m.setInputFiles('[data-avatar]', `${FIX}/generated/person-gps.jpg`); await m.check('[data-consent]'); await ready(m);
  await m.click('[data-start]'); await toResult(m);
  const h = await m.evaluate(() => document.querySelector('[data-compare-view]').getBoundingClientRect().height);
  check('mobile result taller than the old 330px', h > 400, `(${Math.round(h)}px)`);
  await m.screenshot({ path: `${shots}/15-mobile-result.png` });

  check('no JS errors', errors.length === 0, errors.join(' | '));
  await browser.close();
  console.log(`\npassed ${pass}, failed ${fail}`);
  process.exit(fail ? 1 : 0);
})().catch((e) => { console.error(e); process.exit(2); });
